src/Mirror/MirrorSiteBundle/Entity/Attachment.php
<?php
namespace Mirror\MirrorSiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="Mirror\MirrorSiteBundle\Entity\AttachmentRepository")
 */
class Attachment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;

    /**
     * @var \DateTime
     *@ORM\Column(type="datetime")
     */
    protected $when_;

    /**
     * @ORM\Column(type="string", length=20)
     */
    protected $ip;

    /**
     * @ORM\Column(type="integer")
     */
    protected $vote;

    /**
     * @Assert\File(maxSize="40000000")
     */
    private $file;

    /**
     * @return null|string
     */
    public function getAbsolutePath() {
		return null === $this->path
		? null
		: $this->getUploadRootDir().DIRECTORY_SEPARATOR.$this->path;
	}

    /**
     * @return null|string
     */
    public function getWebPath() {
		return null === $this->path
		? null
		: $this->getUploadDir().DIRECTORY_SEPARATOR.$this->path;
	}

    /**
     * @return string
     */
    protected function getUploadRootDir() {
		return __DIR__.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".
        DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."web".DIRECTORY_SEPARATOR.$this->getUploadDir();
	}

    /**
     * @return string
     */
    protected function getUploadDir() {
		return 'bundles'.DIRECTORY_SEPARATOR.'Mirror'.DIRECTORY_SEPARATOR.'uploads';
	}

    /**
     * @param UploadedFile $file
     * @return UploadedFile
     */
    public function setFile(UploadedFile $file) {
        $this->file = $file;
        return $this->file;
    }

    /**
     * @return mixed
     */
    public function getFile() {
        return $this->file;
    }

    /**
     * @return bool
     */
    public function upload()
    {
        $fileStringName = $this->getFile()->getClientOriginalName();
        $fileName = substr($fileStringName, 0, strrpos($fileStringName, '.'));
        $extension = substr($fileStringName, strrpos($fileStringName, '.') + 1);

        $finalSaveName = uniqid().".".$extension;
        $this->path = $finalSaveName;


        $allow = ['jpg', 'png', 'gif', 'mp4', 'ogg'];

        // the file property can be empty if the field is not required
        if (
            null === $this->getFile() ||
            !in_array($extension, $allow) ||
            !strlen($fileName) ||
            !strlen($extension)
        ) {
            return false;
        }

        $this->getFile()->move(
            $this->getUploadRootDir(),
            $finalSaveName
        );

        // set the path property to the filename where you've saved the file

        $this->when_ = new \DateTime();

        // clean up the file property as you won't need it anymore
        $this->file = null;
        return true;
    }

    /**
     * @return bool
     */
    public function rmFromDisk()
    {
        return unlink($this->getAbsolutePath());
    }

    public function getVote() { return $this->vote; }
    /**
     * @param $vote
     * @return int
     */
    public function setVote($vote)
    {
        $this->vote = $vote;
        return $this->vote;
    }

    public function getIp() { return $this->ip; }
    /**
     * @param $ip_address
     * @return bool|string
     */
    public function setIp($ip_address) {
        if( empty($ip_address) ) {
            $this->ip = "Empty addr"; return false;
        }
        $this->ip = $ip_address;
        return $this->ip;
    }

    public function getName() { return $this->name; }
    /**
     * @param $name
     * @return mixed
     */
    public function setName($name) {
        $this->name = $name;
        return $this->name;
    }

    /**
     * @return string
     */
    public function getShortName()
    {
        if( strlen($this->name) > 20 ) return substr($this->name, 0, 19)."..";
        return $this->name;
    }

    public function getPath() { return $this->path; }
    /**
     * @param $path
     * @return mixed
     */
    public function setPath($path) {
        $this->path=$path;
        return $this->path;
    }

    /**
     * @return \DateTime
     */
    public function getWhen_() { return $this->when_; }
    /**
     * @param $when
     * @return mixed
     */
    public function setWhen_($when) {
        $this->when_ = $when;
        return $this->when_;
    }

    public function getId() { return $this->id; }
    /**
     * @param $id
     * @return mixed
     */
    public function setId($id) {
        $this->id = $id;
        return $this->id;
    }

    /**
     * @return string
     */
    public function getExtension() {
        return substr($this->path, strrpos($this->path, '.') + 1);
    }

    /**
     * @return bool
     */
    public function isVideo()
    {
        if( in_array($this->getExtension(), ['mp4', 'ogg']) ) return true;
        return false;
    }

    /**
     * @return bool|string
     */
    public function getVideoType()
    {
        if($this->isVideo()) return "video/".$this->getExtension();
        return false;
    }

    /**
     * @param $upOrDown
     * @return int
     */
    public function voting($upOrDown)
    {
        $upOrDown == 1 ? $this->vote++ : $this->vote--;
        return $this->vote;
    }


}

src/Mirror/MirrorSiteBundle/Entity/User.php
<?php
namespace Mirror\MirrorSiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="app_users")
 * @ORM\Entity
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $password;

    /**
     * @var string
     */
    public $returnPassword;

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

    /**
     * @return bool|string
     */
    public function encryptPass()
    {
        if($this->password == $this->returnPassword) {
            $this->password = password_hash($this->password, PASSWORD_DEFAULT);
            return $this->password;
        }
        return false;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @return null
     */
    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @return array
     */
    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }
}

src/Mirror/MirrorSiteBundle/Controller/UserController.php
<?php
namespace Mirror\MirrorSiteBundle\Controller;

use Mirror\MirrorSiteBundle\Entity\Attachment;
use Mirror\MirrorSiteBundle\Model\TComment;
use Mirror\MirrorSiteBundle\Model\TNavi;
use Mirror\MirrorSiteBundle\Model\TOrderFile;
use Mirror\MirrorSiteBundle\Model\TPost;
use Mirror\MirrorSiteBundle\Exception\InvalidEntityException;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Class PageController
 * @package Mirror\MirrorSiteBunde\Controller
 */
class UserController extends Controller
{
    /**
     * @param $currentPage
     * @param $perPage
     * @param null $sort
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    private function createPage($currentPage, $perPage, $sort = null)
    {
        $this->denyAccessUnlessGranted("ROLE_USER", null, "Access denied.");

        $em = $this->getDoctrine()->getManager();
        $filesCount = $em->getRepository("MirrorMirrorSiteBundle:Attachment")->count();
        $navigation = new TNavi($filesCount, $perPage, $currentPage);
        if( $navigation->pageNotExist() )
            throw $this->createNotFoundException();

        $order = new TOrderFile($sort);
        $files = $em->getRepository("MirrorMirrorSiteBundle:Attachment")
            ->createQueryBuilder('f')->orderBy( $order->getBy(), $order->getHow() )
            ->setFirstResult( $navigation->getFirstResult() )
            ->setMaxResults($perPage)->getQuery()->getResult();


        return $this->render('MirrorMirrorSiteBundle:User:home.html.twig', [
            'PageTitle' => $sort === null ? "home" : $sort,
            'Posts' => $this->getArrayPosts($files),
            'Navi' => $navigation,
            'User' => $this->getUser()
        ]);
    }

    /**
     * @param array $entities
     * @return array
     * @throws \Exception
     */
    private function getArrayPosts(array $entities)
    {
        $em = $this->getDoctrine()->getManager();
        $posts = [];
        foreach($entities as $entity) {
            if(!$entity instanceof Attachment) throw new InvalidEntityException();

            $commentsEntities =  $em->getRepository("MirrorMirrorSiteBundle:Comment")
                ->findByFileIdOrderByWhen( $entity->getId() );

            $comments = [];
            foreach($commentsEntities as $entityComment) {
                $newComment = new TComment($entityComment);
                $newComment->setUser(
                    $em->getRepository("MirrorMirrorSiteBundle:User")->find($entityComment->getUserId())
                );
                $comments[] = $newComment;
            }

            $UserVote = $em->getRepository("MirrorMirrorSiteBundle:Vote")
                ->findUserVoteValue($this->getUser(), $entity);

            $posts[] = new TPost($entity, $comments, $UserVote);
        }
        return $posts;
    }

    /**
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function homeAction($page = 0)
    {
       return $this->createPage($page, 3);
    }

    public function sortAction($page = 0, $sort)
    {
       return $this->createPage($page, 3, $sort);
    }

}

src/Mirror/MirrorSiteBundle/Resources/views/User/home.html.twig
{% extends "MirrorMirrorSiteBundle::logged.html.twig" %}

{% block title %}Mirror|{{ PageTitle }}{% endblock %}

{% block header %}Mirror - {{ PageTitle }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/Mirror/css/main.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('bundles/Mirror/css/header.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/Mirror/css/paginator.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/Mirror/votes/css/vote.css') }}" type="text/css"/>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/Mirror/main.js') }}"></script>
    <script src="{{ asset('bundles/Mirror/voting.js') }}"></script>
    <script src="{{ asset('bundles/Mirror/comment.js') }}"></script>
{% endblock %}

{% block body %}
    <section>
        {% include "MirrorMirrorSiteBundle:User:postsLoop.html.twig" %}
        <div id="footNavi">
            {% if PageTitle == 'home' %}
                {% for i in Navi.max..Navi.min %}
                    {% if i == Navi.current %}
                        <a class="thisLink">{{ i }}</a>
                    {% else %}
                        <a class="pageLinkFoot" href="{{ path('user_home', {'page': i }) }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            {% else %}
                {% for i in Navi.max..Navi.min %}
                    {% if i == Navi.current %}
                        <a class="thisLink">{{ i }}</a>
                    {% else %}
                        <a class="pageLinkFoot" href="{{ path('user_sort', {'sort': PageTitle, 'page': i }) }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}

src/Mirror/MirrorSiteBundle/Resources/views/User/postsLoop.html.twig
{% for item in Posts %}
    <div class="blockCont">
        <div class="block">
            <h1>
                <a href="{{ path('viewer', {'fileName': item.file.path }) }}" aria-label="Name">{{ item.file.shortName }}</a>
                <span id="fileVote{{ item.file.id }}" class="userVoteArea">
                    <i class="icon-thumbs-up voting" title="Upvote" aria-label="Upvote" style="color: {{ item.upVote }};">
                        &#xe800;
                    </i>
                    <span title='Vote' aria-label="Vote">{{ item.file.vote }}</span>
                    <i class="icon-thumbs-down voting" title="Downvote" aria-label="Downvote" style="color: {{ item.downVote }};">
                        &#xe801;
                    </i>
                </span>
                <time aria-label="Added">{{ item.file.when_.format('jS M Y H:i:s') }}</time>
            </h1>
            {% if item.file.isVideo() %}
                <video controls>
                    <source src="/{{ item.file.webPath }}" type="{{ item.file.videoType }}"/>
                </video>
            {% else %}
                <img src="/{{ item.file.webPath }}"/>
            {% endif %}
        </div>
        <div class="commentCont">
            <ul class="comments">
                {% for com in item.comments %}
                    <li>
                        <h5>{{ com.User.username }}<span>{{ com.comment.when.format('d.m.y H:i') }}</span></h5>
                        <div class="commentMessage">{{ com.comment.message }}</div>
                    </li>
                {% endfor %}
                <li style="background: none; border: 0;">
                    <textarea id="newComment{{ item.file.id }}" placeholder="Say something" class="newComments"></textarea>
                </li>
            </ul>

        </div>
    </div>
{% endfor %}